# Generated by Django 5.2.13 on 2026-04-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('miner_uid', models.IntegerField()),
                ('miner_hotkey', models.CharField(db_index=True, max_length=128)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('miner_safety_score', models.FloatField(default=0.0)),
                ('audit_score', models.FloatField(blank=True, null=True)),
                ('accepted_severity', models.FloatField(default=0.0)),
                ('confidence_in_claim', models.FloatField(default=0.0)),
                ('findings_reward', models.FloatField(default=0.0)),
                ('bait_modifier', models.FloatField(default=0.0)),
                ('contribution', models.FloatField(default=0.0)),
                ('n_bait_detected', models.IntegerField(default=0)),
                ('transcript', models.JSONField(default=list)),
                ('hitl_routed', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MinerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('hotkey', models.CharField(db_index=True, max_length=128)),
                ('score', models.FloatField(default=0.0)),
                ('contribution_total', models.FloatField(default=0.0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_hotkey', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('relay_endpoint', models.URLField(max_length=500)),
                ('subnet_type', models.CharField(default='llm-chat', max_length=64)),
                ('categories', models.JSONField(default=list)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_probed_at', models.DateTimeField(blank=True, null=True)),
                ('evaluations_completed', models.PositiveIntegerField(default=0)),
                ('last_evaluation', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('loop_iteration', models.BigIntegerField(default=0)),
                ('last_set_weights_at', models.DateTimeField(blank=True, null=True)),
                ('last_set_weights_block', models.BigIntegerField(blank=True, null=True)),
                ('last_chain_error', models.TextField(blank=True)),
                ('last_chain_error_at', models.DateTimeField(blank=True, null=True)),
                ('chain_connected', models.BooleanField(default=False)),
                ('wallet_loaded', models.BooleanField(default=False)),
                ('wallet_hotkey_ss58', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('severity', models.FloatField()),
                ('summary', models.TextField(blank=True)),
                ('critical', models.BooleanField(db_index=True, default=False)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='validator.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='HitlCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('labeled', 'labeled')], db_index=True, default='pending', max_length=16)),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('labels', models.JSONField(default=list)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hitl', to='validator.evaluation')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='validator.registeredtarget'),
        ),
    ]
