# Generated by Django 5.2.13 on 2026-04-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cycle_block', models.BigIntegerField(db_index=True)),
                ('n_registered', models.IntegerField(default=0)),
                ('n_dispatched', models.IntegerField(default=0)),
                ('n_responded', models.IntegerField(default=0)),
                ('n_earned', models.IntegerField(default=0)),
                ('earned_total', models.FloatField(default=0.0)),
                ('burn_share', models.FloatField(default=0.0)),
                ('owner_uid', models.IntegerField(default=0)),
                ('submitted_weights', models.JSONField(blank=True, default=dict)),
                ('had_fresh_data', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='minerscore',
            name='contribution_total',
        ),
        migrations.RemoveField(
            model_name='minerscore',
            name='score',
        ),
        migrations.AddField(
            model_name='minerscore',
            name='bait_only_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='minerscore',
            name='findings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='minerscore',
            name='last_contribution',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='minerscore',
            name='null_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='minerscore',
            name='submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validatorstatus',
            name='last_burn_share',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='validatorstatus',
            name='last_set_weights_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='validatorstatus',
            name='last_set_weights_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validatorstatus',
            name='owner_uid',
            field=models.IntegerField(default=0),
        ),
    ]
