# Generated by Django 5.2.13 on 2026-04-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_burn_floor_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorstatus',
            name='blocks_until_next_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validatorstatus',
            name='current_block',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validatorstatus',
            name='n_hitl_miners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validatorstatus',
            name='n_probe_miners',
            field=models.IntegerField(default=0),
        ),
    ]
