# Generated by Django 5.2.13 on 2026-04-09 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_status_tick_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='validator.cyclehistory'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='cycle_block_at_creation',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='minerscore',
            name='last_failed_dispatch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minerscore',
            name='last_successful_dispatch_block',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
