# Generated by Django 5.2.13 on 2026-04-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_phase_2_8'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='provenance_turns_verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='provenance_verified',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='RelaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, unique=True)),
                ('miner_hotkey', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_turn_at', models.DateTimeField(auto_now=True)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_sessions', to='validator.registeredtarget')),
            ],
        ),
        migrations.CreateModel(
            name='RelayCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveIntegerField()),
                ('scheme', models.CharField(default='sha256-canonical-json-v1', max_length=64)),
                ('preimage', models.JSONField()),
                ('digest', models.CharField(db_index=True, max_length=128)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('committed_by', models.CharField(max_length=128)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='validator.relaysession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'turn_index'], name='validator_r_session_e25ede_idx')],
                'unique_together': {('session', 'turn_index')},
            },
        ),
    ]
