# Generated by Django 6.0.4 on 2026-04-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0005_provenance_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaitPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_slug', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('detection_cues', models.JSONField(default=list)),
                ('example_prompts', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('related_patterns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'id_slug'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='curated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finding',
            name='curated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='curated_severity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('targets', models.ManyToManyField(blank=True, related_name='customer_profiles', to='validator.registeredtarget')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirm', 'Confirm'), ('downgrade', 'Downgrade'), ('escalate', 'Escalate')], db_index=True, max_length=16)),
                ('reason', models.TextField()),
                ('original_severity', models.FloatField()),
                ('new_severity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_actions', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curation_actions', to='validator.finding')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['finding', '-created_at'], name='validator_c_finding_322728_idx')],
            },
        ),
    ]
