# Generated by Django 5.2.13 on 2026-04-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0007_seed_bait_patterns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('curator_hotkey', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('concern_text', models.TextField()),
                ('detection_cues', models.JSONField(default=list)),
                ('example_prompts', models.JSONField(default=list)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('severity_prior', models.FloatField(default=0.5)),
                ('curator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_concerns', to=settings.AUTH_USER_MODEL)),
                ('related_concerns', models.ManyToManyField(blank=True, related_name='related_from', to='validator.concern')),
            ],
            options={
                'ordering': ['category', 'id_slug'],
            },
        ),
        migrations.AddField(
            model_name='registeredtarget',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='targets', to='validator.concern'),
        ),
        migrations.CreateModel(
            name='ConcernRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='validator.concern')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['concern', '-version'], name='validator_c_concern_8868a5_idx')],
            },
        ),
    ]
