# Generated by Django 6.0.4 on 2026-04-11 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0009_migrate_bait_to_concern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hitlcase',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hitlcase',
            name='dispatched_to_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hitlcase',
            name='labeled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hitlcase',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hitlcase',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_hitl_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hitlcase',
            name='removed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='minerscore',
            name='hitl_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitlcase',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('dispatched', 'dispatched'), ('labeled', 'labeled'), ('timed_out', 'timed_out'), ('removed', 'removed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='PendingContributionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_severity', models.FloatField()),
                ('ground_truth_severity', models.FloatField()),
                ('probe_miner_hotkey', models.CharField(db_index=True, max_length=128)),
                ('probe_miner_uid', models.IntegerField(db_index=True)),
                ('label_source', models.CharField(choices=[('hitl_dispatch', 'HITL dispatch')], default='hitl_dispatch', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('applied', models.BooleanField(db_index=True, default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_adjustments', to='validator.evaluation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
