# Generated by Django 6.0.4 on 2026-04-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0010_hitlcase_removal_and_dispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_text', models.TextField(help_text='The substring, regex, or semantic signature to match against assistant output.')),
                ('kind', models.CharField(choices=[('substring', 'Substring'), ('regex', 'Regex'), ('semantic', 'Semantic (LLM-judged)')], default='substring', max_length=16)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Incremented by the audit pipeline when this cue matches a finding.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='validator.concern')),
            ],
            options={
                'ordering': ['concern_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='matched_cues',
            field=models.ManyToManyField(blank=True, help_text='Which detection cues fired on this finding. Populated by the audit pipeline when a finding is recorded.', related_name='findings', to='validator.detectioncue'),
        ),
        migrations.CreateModel(
            name='UserTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_text', models.TextField(help_text='The input-side framing a miner can use as a seed for probe generation.')),
                ('kind', models.CharField(choices=[('prompt', 'Prompt (direct user input)'), ('persona', 'Persona (user role/framing)'), ('context', 'Context (situational pressure)')], default='prompt', max_length=16)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('invocation_count', models.PositiveIntegerField(default=0, help_text='Incremented each time the audit pipeline associates a probe with this trigger.')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Incremented each time a probe seeded from this trigger produced a finding (any cue matched).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='validator.concern')),
            ],
            options={
                'ordering': ['concern_id', 'id'],
            },
        ),
    ]
