# Generated by Django 6.0.4 on 2026-04-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0017_evaluation_extracted_claims_experiment_field_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedclaim',
            name='value_date',
        ),
        migrations.RemoveField(
            model_name='extractedclaim',
            name='value_numeric',
        ),
    ]
