# Generated by Django 6.0.4 on 2026-04-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0019_experiment_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_text', models.TextField(help_text='Short declarative harm phrase used as the {behavior} input to the HarmBench classifier template.')),
                ('source_ref', models.CharField(db_index=True, help_text="Provenance marker: 'harmbench:<BehaviorID>' or 'native:<slug>'. Unique for idempotent ingestion.", max_length=128, unique=True)),
                ('context_string', models.TextField(blank=True, help_text='Populated for contextual-class behaviors; prepended to the prompt at dispatch time.')),
                ('functional_category', models.CharField(choices=[('standard', 'Standard (direct harmful request)'), ('contextual', 'Contextual (requires context string)'), ('copyright', 'Copyright (verbatim reproduction)')], default='standard', max_length=16)),
                ('semantic_category', models.CharField(blank=True, db_index=True, help_text='HarmBench SemanticCategory when sourced from HarmBench (chemical_biological, cybercrime_intrusion, etc.); free-form otherwise.', max_length=64)),
                ('active', models.BooleanField(db_index=True, default=False, help_text='Off by default on ingestion — operator opts individual behaviors in via the UI.')),
                ('probe_count', models.PositiveIntegerField(default=0, help_text='Incremented each time a miner probe targets or surfaces this behavior.')),
                ('fire_count', models.PositiveIntegerField(default=0, help_text="Incremented when the HarmBench classifier returns 'yes' with high confidence against this behavior.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concerns', models.ManyToManyField(blank=True, help_text='Concerns this behavior contributes to. One behavior can belong to multiple concerns.', related_name='behaviors', to='validator.concern')),
            ],
            options={
                'ordering': ['semantic_category', 'source_ref'],
            },
        ),
    ]
