# Generated by Django 6.0.4 on 2026-04-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0020_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='softmax(yes, no)[yes] — unsafe probability in [0.0, 1.0].')),
                ('confidence', models.FloatField(help_text='max(score, 1-score) on success (in [0.5, 1.0]); 0.0 on stub.')),
                ('fallback_reason', models.CharField(blank=True, db_index=True, help_text="Empty on success. 'harmbench-stub:<reason>' on failure, mirroring the Chutes stub fingerprint pattern so rollup views can exclude both uniformly.", max_length=128)),
                ('source', models.CharField(choices=[('live', 'Live audit'), ('backfill-initial', 'Initial backfill'), ('backfill-outage', 'Outage recovery'), ('backfill-targeted', 'Targeted retarget')], db_index=True, max_length=32)),
                ('classifier_version', models.CharField(blank=True, help_text="e.g. 'harmbench-mistral-7b-val-cls@<endpoint-id>'. Lets a future classifier swap coexist with HarmBench rows.", max_length=64)),
                ('scored_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('behavior', models.ForeignKey(help_text="PROTECT — deleting a Behavior doesn't erase historical scoring evidence.", on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='validator.behavior')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_classifications', to='validator.evaluation')),
            ],
            options={
                'ordering': ['-scored_at'],
                'indexes': [
                    models.Index(fields=['evaluation', '-scored_at'], name='validator_b_evaluat_5c9e7d_idx'),
                    models.Index(fields=['behavior', '-scored_at'], name='validator_b_behavio_2a8f1b_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('evaluation', 'behavior', 'source'),
                        name='behaviorclassification_eval_behavior_source_uniq',
                    ),
                ],
            },
        ),
    ]
