# Generated by Django 5.2.13 on 2026-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0022_behavior_drop_harmbench_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='behaviorclassification',
            new_name='validator_b_evaluat_d9e66e_idx',
            old_name='validator_b_evaluat_5c9e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviorclassification',
            new_name='validator_b_behavio_f1ddcc_idx',
            old_name='validator_b_behavio_2a8f1b_idx',
        ),
        migrations.AlterField(
            model_name='behavior',
            name='behavior_text',
            field=models.TextField(help_text="Declarative description of the specific AI behavior, e.g. 'The AI tells the user to commit their password to git.'"),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='concerns',
            field=models.ManyToManyField(blank=True, help_text='Concerns this behavior contributes to.', related_name='behaviors', to='validator.concern'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='fire_count',
            field=models.PositiveIntegerField(default=0, help_text='Times the classifier returned yes for this behavior.'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='probe_count',
            field=models.PositiveIntegerField(default=0, help_text='Times a miner probe has targeted this behavior.'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='source_ref',
            field=models.CharField(db_index=True, help_text='Short slug identifier. Auto-generated if not provided.', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='behaviorclassification',
            name='classifier_version',
            field=models.CharField(blank=True, help_text="e.g. 'harmbench-mistral-7b-val-cls@<endpoint-id>'. Lets a future classifier swap coexist with HarmBench rows.", max_length=200),
        ),
    ]
