# Generated by Django 6.0.4 on 2026-05-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0025_evaluation_reasoning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='show_on_stats',
            field=models.BooleanField(db_index=True, default=True, help_text='Controls whether this concern appears on the public stats/ heatmap. Independent of active.'),
        ),
        migrations.AddField(
            model_name='registeredtarget',
            name='show_on_stats',
            field=models.BooleanField(db_index=True, default=True, help_text='Controls whether this target appears on the public stats/ heatmap. Independent of active.'),
        ),
    ]
