# Generated by Django 5.2.13 on 2026-05-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0026_stats_visibility_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_from', models.DateField(blank=True, help_text='Exclude evaluations before this date from public stats. Null = no lower bound.', null=True)),
                ('stats_to', models.DateField(blank=True, help_text='Exclude evaluations after this date from public stats. Null = no upper bound.', null=True)),
            ],
        ),
    ]
